modLoader="javafml" #mandatory

loaderVersion="[38,)" #mandatory (37 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="easy_steel" #mandatory
version="1.5.1" #mandatory
displayName="Easy Steel & More" #mandatory
description='''
Adds steel, bronze, titanium, hardened steel, and tungsten-carbide gear
'''


[[dependencies.easy_steel]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.easy_steel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18]"
    ordering="NONE"
    side="BOTH"
